### ISSUE TITLE
Dynamically pass banner image URL to <ImageHeader />

### ISSUE THREAD

**Issue by GetPsyched** [nitkkr-dev/nitkkr#128]
Currently, `<ImageHeader />` sets its background by taking in a `className` prop with a Tailwind class like `bg-[url('https://foo.bar')]` but we want this to be dynamic. For some reason, Tailwind doesn't read dynamically passed URLs like `bg-[url(${someUrlVariable})]`.

**Comment by heydoyouknowme0** [comment]
Tailwind cannot build [dynamic classes](https://tailwindcss.com/docs/content-configuration#dynamic-class-names), just using style tag for this should be fine I think

**Comment by heydoyouknowme0** [comment]
https://github.com/kiahjh/next-bg-image
