### ISSUE TITLE
About Institute

### ISSUE THREAD

**Issue by GetPsyched** [nitkkr-dev/nitkkr#2]
## Things to be done

- [ ] #19
- [ ] #20
- [ ] #21
- [ ] #22

**Comment by ranjanmangla1** [comment]
please assign me this issue, I would love to work on it

**Comment by GetPsyched** [comment]
I appreciate the enthusiasm, but we don't have designs ready for this page yet so we cannot assign it to anyone at the moment. Will keep you in mind once the design's are ready

**Comment by GetPsyched** [comment]
No more need for tracking issue
