### ISSUE TITLE
Component generics

### ISSUE THREAD

**Issue by GetPsyched** [nitkkr-dev/nitkkr#32]
Much like #29, we have some components that we need to design that aren't an input. These will mainly serve as a layout that pages can inherit and modify.

Overview:
- [x] Button (#106)
  - [ ] Edit/Delete
  - [ ] Navigation buttons (arrow key, etc.)
- [x] Table (#116)

 Might add a few more here later

**Comment by ranjanmangla1** [comment]
@GetPsyched If no one is working on it, Please assign to me
