### ISSUE TITLE
Departments

### ISSUE THREAD

**Issue by GetPsyched** [nitkkr-dev/nitkkr#44]
Each department of the college gets its own dedicated page. While the website has it very segregated into sub-pages, we'll do things differently.

A department's page will primarily consist of the following, in order:
- [ ] About
- [ ] Vision & Mission
- [ ] HOD's message
- [ ] Programs
  - [ ] Under-graduate (Scheme & Syllabi)
  - [ ] Post-graduate (Scheme & Syllabi)
  - [ ] Doctoral/Ph.D
- [ ] Cards
  - [ ] Faculty
  - [ ] Staff
  - [ ] Laboratories
  - [ ] Achievements
  - [ ] Photo Gallery
  - [ ] Misc. (one for each unique section)

#### Notes
- Doctoral should have a list of professors accepting nominations instead of putting it on their profile.

**Comment by KambojRajan** [comment]
Sorry to be silly, can you pls tell me where to fetch the design for this 
thanx

**Comment by GetPsyched** [comment]
Completed in #127
