### ISSUE TITLE
Next-Auth not working with Prisma (Edge Runtime Issues)

### ISSUE THREAD

**Issue by geekysilento** [nitkkr-dev/nitkkr#86]

**Comment by geekysilento** [comment]
Fix inprogress
- Managed to get Prisma setup with Next.js's middleware.ts (running on Edge) using Prisma Accelerate and Re-Configured Prisma with Next-Auth

**Comment by GetPsyched** [comment]
Fixed by ditching Prisma

**Comment by GetPsyched** [comment]
Fixed by ditching Prisma
